# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: tr-TR

# Site title
title: "P-DOCU"

# A description of your site for meta tag, search engine results.
description: "Farklı bir yer, farklı bir şey, farklı konular."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: " "

# The base hostname & protocol of your site for where absolute urls are needed.
url: ""

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-V4H1EYNNQ0"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Anasayfa
    url: /home
  - text: Blog
    url: /index
  - text: Ben Kimim?
    url: /about
  - text: Kategoriler
    url: /tags
  - text: Linkler
    url: /404

# The shortname for your Disqus site to enable comments.
disqus:

# Colors
accent_color: '#517664'

# Site footer
footer:
  content: "&copy; 2023 Tüm Hakları Saklı Falan Değil Tepe Tepe Kullanın by P-DOCU"
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
